services:
  # Backend API
  - type: web
    name: registro-ponto-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --config gunicorn.conf.py app:app"
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_ENV
        value: production

  # Frontend Static Site
  - type: static
    name: registro-ponto-frontend
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: registro-ponto-api
          property: host
