services:
  # Backend API
  - type: web
    name: registro-ponto-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --config gunicorn.conf.py app:app"
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_ENV
        value: production
